image: node:latest

stages:
    - build
    - test
    - deploy

# I'm not entirely sure about this, but it might be necessary for dependencies
cache:
    paths:
        - frontend/node_modules/

build-frontend:
    stage: build
    script:
        - cd frontend
        - npm install
        # not entirely sure why CI environment var should be set to false
        - CI=false npm run-script build
        - echo "built frontend"

# TODO
# test-postman:
#     stage: test
#     image:
#         # command line collection runner, defined in docker image
#         name: postman/newman:alpine
#         entrypoint: [""]
#     script:
        # TODO add script here when ready! the format will be like
        # newman run <file_name>.json

# TODO
# test-selenium:
#     stage: test
#     image: python:3.9-slim
#     services:
#         # run in chrome browser
#         - selenium/standalone-chrome
    # TODO uncomment when ready!
    # before_script:
    #     - python3 -m pip install -r frontend/selenium/requirements.txt
    # script:
    #     - cd frontend/selenium
    #     - python3 -m pytest

# TODO 
# test-jest:
#     stage: test
#     image: node:latest
#     script:
#         - cd frontend
#         - npm install
#         # suppress output when running
#         - npm test --silent
