// React imports
import { Link, useParams } from 'react-router-dom';
import React, { useState, useEffect } from 'react';
// Library imports
import axios from 'axios';
import Button from 'react-bootstrap/Button';
// Local imports
import { GALLERIES_NUM_IDS } from './Galleries';
import './InstanceModels.css';
import { youtubeKey } from '../../API_keys/Keys.js';


const GalleryInstance = () => {
  const galleryId = useParams().galleryId;
  const [galleryData, setGalleryData] = useState({});
  // const [artworkInfo, setArtworkInfo] = useState({});
  // const [artistInfo, setArtistInfo] = useState({});
  const [videoSrc, setVideoSrc] = useState("");

  // Run only once due to second arg
  useEffect(() => {
    console.log("page loaded")
    axios.get(`https://galleryguide.me/api/galleries/${ galleryId }`)
    .then(response => {
      const galleryData = response.data;
      setGalleryData(galleryData);
      console.log("response data: ", galleryData);

      // Get media
      console.log("getting src for gallery ", galleryData.name)
      axios.get(`https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=1&q=${ galleryData.name }&type=video&key=${ youtubeKey.key }`)
      .then(response => {
        console.log("youtube video data: ", response.data);
        setVideoSrc(`https://www.youtube.com/embed/${ response.data.items[0].id.videoId }`)
        console.log("src in request: ", videoSrc);
      })
      .catch((error) => {
        console.log("axios error when fetching video: ", error);
      })
    })
    .catch((error) => {
      console.log("axios error: ", error);
    })

    // Get artwork and artist information
    // if (galleryData.description) {
      // TODO filter artworks by gallery id
      // axios.get(`https://galleryguide.me/api/artworks/${ galleryData.artwork_id }`)
      // .then(response => {
      //   setArtworkData(response.data);
      //   console.log("artwork data: ", artworkData);
      // })
      // .catch((error) => {
      //   console.log("axios error while getting artwork info: ", error);
      // })
      // // TODO filter artists by gallery id
      // axios.get(`https://galleryguide.me/api/artists/${ artworkData.artist_id }`)
      // .then(response => {
      //   setArtistInfo(response.data);
      //   console.log("artist data: ", artistInfo);
      // })
      // .catch((error) => {
      //   console.log("axios error while getting artist info: ", error);
      // })
    // }
  }, [])

  // Check that we got a valid ID request
  if (galleryId < 1 || galleryId > GALLERIES_NUM_IDS) {
    return (
      <div>
        <h1>Oops...!</h1>
        {/* Tara's note: &#41; is the html code for a closing parenthesis, ) */}
        <p>How did you get here? We don't have a gallery with identification #{ galleryId }. Let us know if you think this is our error. :&#41;</p>
      </div>
    );
  }

  // Tara's note: there's a lot more potential data we can add in Phase 3 to make this look prettier!
  //change to be relevant to galleries
  return (
    <div>
      <div class="art-instance-image-description-wrapper">
        <img class="art-instance-img" src={ galleryData.thumbnail } alt="Artwork visual representation"/>
        <div class="art-instance-description">
          <h1>{ galleryData.name }</h1>
          <em>{ galleryData.description }</em>
          <br/>
          <br/>
          <p>Located in { galleryData.region }</p>
          <p>Number of artists hosted: { galleryData.num_artists }</p>
          <p>Number of artworks hosted: { galleryData.num_artworks }</p>
          <p><a href={ galleryData.website }>Gallery website</a></p>
          <p>This gallery is stored as ID #{ galleryData.id } in GalleryGuide.</p>
        </div>
      </div>

      {/* More media */}
      <div>
        <h2>Media for a more immersive experience</h2>
        <p>Note that these results are generated by a search. Results are not curated and GalleryGuide takes no ownership of generated results.</p>
        <iframe width="420" height="315" src={videoSrc}></iframe>
      </div>

      {/* TODO #? Add connections to other instances */}

      <Link to={'/galleries'}>
        <Button>&#60;</Button> Back to main galleries page
      </Link>
    </div>
  )
};

export default GalleryInstance;
